// src/utils/mockData.ts

import { Product, Category } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Panneaux Solaires',
    slug: 'panneaux-solaires',
    description: 'Panneaux photovoltaïques de qualité',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400',
  },
  {
    id: '2',
    name: 'Batteries',
    slug: 'batteries',
    description: 'Batteries solaires longue durée',
    image: 'https://images.unsplash.com/photo-1591290619762-c588e5cb8179?w=400',
  },
  {
    id: '3',
    name: 'Onduleurs',
    slug: 'onduleurs',
    description: 'Onduleurs et régulateurs',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400',
  },
  {
    id: '4',
    name: 'Kits Solaires',
    slug: 'kits-solaires',
    description: 'Kits complets prêts à installer',
    image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=400',
  },
  {
    id: '5',
    name: 'Accessoires',
    slug: 'accessoires',
    description: 'Câbles, supports et accessoires',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400',
  },
  {
    id: '6',
    name: 'Éclairage Solaire',
    slug: 'eclairage-solaire',
    description: 'Lampes et projecteurs solaires',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Panneau Solaire 500W Monocristallin',
    description: 'Panneau solaire haute efficacité avec cellules monocristallines de dernière génération. Rendement optimal même par faible luminosité.',
    price: 250000,
    categoryId: '1',
    images: ['https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400'],
    stock: 15,
    specifications: {
      'Puissance': '500W',
      'Type': 'Monocristallin',
      'Tension': '24V',
      'Efficacité': '21%',
      'Dimensions': '2000 x 1000 x 40mm',
      'Poids': '25kg',
      'Garantie': '25 ans',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Batterie Lithium 200Ah 12V',
    description: 'Batterie lithium-ion longue durée avec BMS intégré. Plus de 6000 cycles de charge.',
    price: 450000,
    categoryId: '2',
    images: ['https://images.unsplash.com/photo-1591290619762-c588e5cb8179?w=400'],
    stock: 8,
    specifications: {
      'Capacité': '200Ah',
      'Tension': '12V',
      'Type': 'LiFePO4',
      'Cycles': '6000+',
      'Poids': '22kg',
      'Garantie': '5 ans',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Onduleur Hybride 5KW',
    description: 'Onduleur hybride avec régulateur MPPT intégré. Compatible réseau et hors réseau.',
    price: 350000,
    categoryId: '3',
    images: ['https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400'],
    stock: 12,
    specifications: {
      'Puissance': '5000W',
      'Type': 'Hybride',
      'Tension entrée': '48V',
      'Tension sortie': '220V',
      'MPPT': 'Oui',
      'Garantie': '3 ans',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Kit Solaire Complet 3KW',
    description: 'Installation complète prête à installer : panneaux, batteries, onduleur, câbles et accessoires.',
    price: 1500000,
    categoryId: '4',
    images: ['https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=400'],
    stock: 5,
    specifications: {
      'Puissance': '3000W',
      'Panneaux': '6x 500W',
      'Batteries': '2x 200Ah',
      'Onduleur': '5KW',
      'Installation': 'Incluse',
      'Garantie': '2 ans',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Panneau Solaire 300W Polycristallin',
    description: 'Excellent rapport qualité-prix. Idéal pour les installations résidentielles.',
    price: 180000,
    categoryId: '1',
    images: ['https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400'],
    stock: 20,
    specifications: {
      'Puissance': '300W',
      'Type': 'Polycristallin',
      'Tension': '12V',
      'Efficacité': '17%',
      'Dimensions': '1650 x 990 x 35mm',
      'Garantie': '15 ans',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Batterie AGM 150Ah 12V',
    description: 'Batterie robuste et fiable pour installations solaires. Excellente durée de vie.',
    price: 280000,
    categoryId: '2',
    images: ['https://images.unsplash.com/photo-1591290619762-c588e5cb8179?w=400'],
    stock: 10,
    specifications: {
      'Capacité': '150Ah',
      'Tension': '12V',
      'Type': 'AGM',
      'Cycles': '1200',
      'Poids': '45kg',
      'Garantie': '3 ans',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
